name = Front
description = Front page layout.
preview = preview.png
template = front-layout

; Regions
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar
regions[footer] = Footer

; Stylesheets
stylesheets[all][] = css/layouts/front/front.layout.css
